name: Deploy to PROD
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows the workflow to be manually triggered.

jobs:
  build_and_deploy:
    if: (contains(fromJSON('["annesiri", "ssb-cgn", "Glenruben", "johnnadeluy", "Carl-OW"]'), github.actor))
    name: Build, push and deploy
    runs-on: ubuntu-latest
    environment: "production"
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Generate vulnerability report
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: "fs"
          format: "cyclonedx"
          output: "dependency-results.sbom.json"
          scan-ref: "."
      - name: Build and push image and SBOM to OCI registry
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5 # v0
        id: docker-build-push
        with:
          team: ssbno
          tag: latest
          byosbom: "dependency-results.sbom.json"
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ secrets.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: Deploy to Nais
        uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          TEAM: ssbno
          CLUSTER: prod
          RESOURCE: .nais/prod.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-build-push.outputs.telemetry }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
